-- PostgreSQL migration generated from SQLite database: stllhaus.db
-- Generated on 2026-03-22
BEGIN;

DROP TABLE IF EXISTS "balance_entries" CASCADE;
CREATE TABLE "balance_entries" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "date" TIMESTAMP,
    "account" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "description" TEXT
);

DROP TABLE IF EXISTS "expenses" CASCADE;
CREATE TABLE "expenses" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "date" TIMESTAMP,
    "amount" DOUBLE PRECISION NOT NULL,
    "category" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "paid_from" TEXT DEFAULT 'sales'
);

DROP TABLE IF EXISTS "inventory" CASCADE;
CREATE TABLE "inventory" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "quantity" DOUBLE PRECISION NOT NULL,
    "unit" TEXT NOT NULL,
    "cost_per_unit" DOUBLE PRECISION,
    "date_purchased" TIMESTAMP,
    "notes" TEXT
);

DROP TABLE IF EXISTS "menu_items" CASCADE;
CREATE TABLE "menu_items" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "category" TEXT NOT NULL,
    "is_hidden" BOOLEAN DEFAULT FALSE NOT NULL,
    "is_sold_out" BOOLEAN DEFAULT FALSE NOT NULL
);

DROP TABLE IF EXISTS "preorders" CASCADE;
CREATE TABLE "preorders" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "customer_name" TEXT NOT NULL,
    "pickup_time" TIMESTAMP NOT NULL,
    "items" JSONB NOT NULL,
    "notes" TEXT,
    "status" TEXT NOT NULL,
    "created_at" TIMESTAMP
);

DROP TABLE IF EXISTS "sales" CASCADE;
CREATE TABLE "sales" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "date" TIMESTAMP,
    "items" JSONB NOT NULL,
    "subtotal" DOUBLE PRECISION NOT NULL,
    "payment_method" TEXT NOT NULL,
    "daily_order_number" INTEGER,
    "customer_name" TEXT,
    "discount" DOUBLE PRECISION DEFAULT 0.0 NOT NULL
);

DROP TABLE IF EXISTS "stock_logs" CASCADE;
CREATE TABLE "stock_logs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "date" TIMESTAMP,
    "item_id" INTEGER,
    "item_name" TEXT NOT NULL,
    "category" TEXT,
    "action" TEXT NOT NULL,
    "delta" DOUBLE PRECISION NOT NULL,
    "quantity_after" DOUBLE PRECISION,
    "unit" TEXT,
    "notes" TEXT
);

DROP TABLE IF EXISTS "tabs" CASCADE;
CREATE TABLE "tabs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "customer_name" TEXT NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "direction" TEXT NOT NULL,
    "description" TEXT,
    "date" TIMESTAMP,
    "status" TEXT NOT NULL,
    "settled_at" TIMESTAMP
);

CREATE INDEX "ix_balance_entries_id" ON "balance_entries" ("id");
CREATE INDEX "ix_expenses_id" ON "expenses" ("id");
CREATE INDEX "ix_menu_items_id" ON "menu_items" ("id");
CREATE INDEX "ix_preorders_id" ON "preorders" ("id");
CREATE INDEX "ix_sales_id" ON "sales" ("id");
CREATE INDEX "ix_stock_logs_id" ON "stock_logs" ("id");
CREATE INDEX "ix_tabs_id" ON "tabs" ("id");

INSERT INTO "balance_entries" ("id", "date", "account", "amount", "description") VALUES
    (1, '2026-03-07 00:45:46.717877', 'cash', 60.0, 'Sales from 1st of March and 28th of Feb'),
    (2, '2026-03-08 21:55:18.543048', 'bank', 555.51, 'Sales from 7 March'),
    (3, '2026-03-08 21:57:07.929543', 'cash', 435.0, 'Sales from 7th of March'),
    (4, '2026-03-08 21:58:55.422852', 'cash', -10.0, '1x Condensed Highlander 1x Ice'),
    (5, '2026-03-08 22:00:19.476372', 'bank', -152.68, 'Return to NZHL'),
    (6, '2026-03-08 22:00:30.820394', 'bank', -30.0, 'Return to BDO'),
    (7, '2026-03-10 01:30:45.890046', 'bank', 20.0, 'Sales from 9th of march'),
    (8, '2026-03-10 01:31:24.464221', 'bank', 50.0, 'sales from 8th of march'),
    (9, '2026-03-10 01:31:55.030862', 'bank', 50.0, 'from westpac accounts sales from 7th of march'),
    (10, '2026-03-10 01:32:31.726140', 'bank', -258.96, 'Bought Ref for Storage purposes'),
    (11, '2026-03-11 00:07:25.771618', 'cash', -40.0, 'bought ingredients.'),
    (12, '2026-03-11 00:21:21.119760', 'cash', -50.0, 'need for sink coffee cart'),
    (13, '2026-03-11 14:15:28.998972', 'bank', -205.0, 'Borrowed by Anty Mean'),
    (14, '2026-03-12 18:19:10.104363', 'bank', 200.0, 'credit from anty mean'),
    (15, '2026-03-12 18:19:23.881859', 'bank', -90.0, 'Bought Thea matcha and spoon'),
    (16, '2026-03-12 18:29:19.433596', 'bank', 30.0, 'Sales from 11th of March'),
    (17, '2026-03-13 15:44:11.387950', 'cash', -45.76, 'Bought cups from hardy and pack centre'),
    (20, '2026-03-14 18:27:06.488742', 'bank', -69.78, 'Pak n Save (Stock)'),
    (21, '2026-03-14 18:27:23.766951', 'bank', -23.34, 'Woolworths (Stock)'),
    (22, '2026-03-14 18:28:43.800959', 'bank', 40.0, 'Sales from 14th of March'),
    (23, '2026-03-14 18:29:17.779659', 'bank', 70.0, 'sales from 13th of March'),
    (24, '2026-03-14 18:29:36.651867', 'cash', 20.0, 'sales from 14th of March'),
    (25, '2026-03-14 21:49:07.333389', 'bank', 50.0, 'Sales from 12th of March'),
    (26, '2026-03-15 18:40:45.526207', 'cash', 58.0, 'Sales from 15th of March'),
    (27, '2026-03-18 18:28:40.333207', 'cash', -300.0, 'Business Registration'),
    (28, '2026-03-18 18:28:57.982949', 'bank', -66.0, 'Business Registration');

SELECT setval(pg_get_serial_sequence('balance_entries', 'id'), 28, true);

INSERT INTO "expenses" ("id", "date", "amount", "category", "description", "paid_from") VALUES
    (1, '2026-03-06 09:56:22.995769', 9.18, 'Ingredients', '2 OTIS Oat Milk from Pak n Save', 'sales'),
    (3, '2026-03-07 15:23:36.714368', 20.0, 'Other', 'food', 'sales'),
    (4, '2026-03-07 16:24:29.636718', 6.0, 'Other', 'drink', 'sales'),
    (5, '2026-03-07 20:58:54.160526', 10.0, 'Other', 'food', 'sales'),
    (10, '2026-03-01 12:00:00.000000', 11.85, 'Ingredients', '3.0 bottles of Ferna Primera Ube (Tita Chrtisty)', 'sales'),
    (12, '2026-03-06 12:00:00.000000', 9.18, 'Ingredients', '2.0 cartons of Otis Oat Milk (Pak n Save)', 'sales'),
    (13, '2026-03-01 12:00:00.000000', 20.94, 'Other', '6.0 cartons of UFC Refresh Coconut Water 1L (Pak n Save)', 'sales'),
    (15, '2026-03-06 12:00:00.000000', 33.5, 'Ingredients', '2.0 bottles of Anchor Cream 2L (Pak n Save)', 'sales'),
    (16, '2026-03-01 12:00:00.000000', 16.75, 'Ingredients', '1.0 bottles of Anchor Cream 2L (Pak n Save)', 'sales'),
    (17, '2026-03-06 12:00:00.000000', 11.85, 'Ingredients', '3.0 bottles of Ferna Primera Ube (Tita Christy)', 'sales'),
    (18, '2026-03-04 12:00:00.000000', 9.98, 'Ingredients', '2.0 jars of Jersey Condensed Mlk Ube (Tita Christy)', 'own'),
    (19, '2026-03-06 12:00:00.000000', 13.95, 'Ingredients', '1.0 cartons of Goldena Sago''t Gulaman Syrup (Tita Christy)', 'sales'),
    (20, '2026-03-04 12:00:00.000000', 11.97, 'Ingredients', '3.0 jars of Nestle Highlander Condensed Mlk (Pak n Save)', 'sales'),
    (21, '2026-03-06 12:00:00.000000', 4.29, 'Ingredients', '1.0 cartons of Nestle Highlander Condensed Mlk (Woolsworth)', 'sales'),
    (22, '2026-03-06 12:00:00.000000', 19.56, 'Ingredients', '4.0 cartons of Otis Oat Milk (Woolsworth)', 'sales'),
    (23, '2026-02-26 12:00:00.000000', 9.66, 'Ingredients', '2.0 bottles of Anchor Cream 500ml (Woolworths (Testing))', 'own'),
    (24, '2026-02-22 12:00:00.000000', 4.29, 'Other', '1.0 cartons of UFC Refresh Coconut Water 1L (Woolworth (testing))', 'own'),
    (25, '2026-03-01 12:00:00.000000', 4.5, 'Other', '350.0 g of Strawberry (Fresh)', 'own'),
    (26, '2026-02-25 12:00:00.000000', 4.29, 'Other', '1.0 cartons of UFC Refresh Coconut Water1L (Woolworth (Testing))', 'own'),
    (27, '2026-02-28 12:00:00.000000', 2.5, 'Equipment', '1.0 cartons of Gloves (Look sharp)', 'own'),
    (28, '2026-02-28 12:00:00.000000', 4.5, 'Ingredients', '1.0 cartons of Ziplock 125pcs', 'own'),
    (29, '2026-02-28 12:00:00.000000', 6.0, 'Packaging', '1.0 bags of double wall cups (Looksharp (Used Lids only))', 'own'),
    (30, '2026-02-26 12:00:00.000000', 5.0, 'Equipment', '1.0 bags of 3pc Squeeze Bottle (Looksharp)', 'own'),
    (31, '2026-03-01 12:00:00.000000', 9.0, 'Packaging', '2.0 bags of 420ML tall cups (Warehouse (used for weekend pour))', 'own'),
    (32, '2026-03-05 12:00:00.000000', 13.89, 'Packaging', '1.0 bags of Bio Clear Cup PLA 420ml 50s', 'sales'),
    (33, '2026-03-05 12:00:00.000000', 14.93, 'Packaging', '1.0 bags of Bio Clear Cup PLA 500ml 50s (Gilmours)', 'own'),
    (34, '2026-03-05 12:00:00.000000', 14.93, 'Packaging', '1.0 bags of Bio Clear Cup PLA 500ml 50s (Gilmours)', 'sales'),
    (35, '2026-03-05 12:00:00.000000', 9.72, 'Packaging', '1.0 bags of Bio Clear Lids 100pk (Gilmours)', 'sales'),
    (36, '2026-03-05 12:00:00.000000', 2.5, 'Other', '1.0 bags of Coastal Napkin 100ea (Gilmours)', 'sales'),
    (37, '2026-03-05 12:00:00.000000', 12.78, 'Packaging', '1.0 bags of 2 Cup Carrier Tray (Gilmours)', 'sales'),
    (38, '2026-03-05 12:00:00.000000', 12.78, 'Equipment', '1.0 cartons of Gloves', 'sales'),
    (39, '2026-03-05 12:00:00.000000', 5.98, 'Packaging', '1.0 cartons of Sugarcane Straw 100pk (Gilmours)', 'sales'),
    (40, '2026-03-06 12:00:00.000000', 4.15, 'Other', '1.0 bags of Kitchen Towel (Woolworth)', 'sales'),
    (41, '2026-03-06 12:00:00.000000', 8.6, 'Other', '2.0 cartons of Party Ice 3kg (Woolworths)', 'sales'),
    (42, '2026-02-26 12:00:00.000000', 14.93, 'Packaging', '1.0 bags of Bio Clear Cup PLA 500ml 50s (Gilmours)', 'own'),
    (43, '2026-02-26 12:00:00.000000', 9.72, 'Packaging', '1.0 bags of Bio Clear Lids 100pk (Gilmours)', 'own'),
    (44, '2026-03-01 12:00:00.000000', 15.56, 'Ingredients', '4.0 cartons of Otis Oat Milk (Woolworth)', 'sales'),
    (45, '2026-02-27 12:00:00.000000', 10.95, 'Ingredients', '1.0 bags of Laffare Gusto Plunger 200g (Woolworth)', 'own'),
    (46, '2026-02-27 12:00:00.000000', 3.6, 'Ingredients', '1.0 jars of Nestle Highlander Condensed Mlk', 'own'),
    (47, '2026-02-25 12:00:00.000000', 4.29, 'Other', '1.0 cartons of UFC Refresh Coconut Water 1L (woolworth)', 'own'),
    (48, '2026-03-04 12:00:00.000000', 16.98, 'Ingredients', '2.0 bags of Laffare Gusto Plunger 200g (Pak n Save)', 'sales'),
    (49, '2026-03-04 12:00:00.000000', 23.94, 'Other', '6.0 cartons of UFC Refresh Coconut Water 1L (Pak n Save)', 'sales'),
    (50, '2026-03-08 12:00:00.000000', 4.3, 'Other', '1.0 bags of Party Ice 3kg (Woolworth)', 'sales'),
    (51, '2026-03-08 12:00:00.000000', 3.6, 'Ingredients', '1.0 jars of Nestle Highlander Condensed Mlk (Woolworth)', 'sales'),
    (52, '2026-03-06 12:00:00.000000', 15.6, 'Equipment', '4.0 pcs of Display Stand', 'own'),
    (53, '2026-02-24 12:00:00.000000', 80.0, 'Ingredients', '1.0 bags of Thea Matcha 100g (Thea Matcha)', 'own'),
    (54, '2026-02-24 12:00:00.000000', 35.0, 'Ingredients', '1.0 bags of Elufa Ube Powder 1kg (Eve''s Shoppe)', 'own'),
    (55, '2026-02-25 12:00:00.000000', 42.9, 'Ingredients', '1.0 cartons of Milklab Oat Milk (Aitkens)', 'own'),
    (56, '2026-03-11 12:00:00.000000', 15.56, 'Ingredients', '4.0 cartons of Otis Oat Milk (Woolworths)', 'sales'),
    (57, '2026-03-11 12:00:00.000000', 12.87, 'Other', '3.0 cartons of UFC Refresh Coconut Water 1L (woolworth)', 'sales'),
    (58, '2026-03-11 12:00:00.000000', 10.8, 'Ingredients', '3.0 jars of Nestle Highlander Condensed Mlk (Woolworth)', 'sales'),
    (59, '2026-03-13 12:00:00.000000', 11.82, 'Packaging', '1.0 bags of Glass PET plastic 420ML (Hardy Packaging)', 'sales'),
    (60, '2026-03-13 12:00:00.000000', 7.8, 'Packaging', '1.0 bags of LID Domed for 420ML PET (Hardy Packaging)', 'sales'),
    (61, '2026-03-13 12:00:00.000000', 16.82, 'Packaging', '1.0 bags of BIOPAK Clear 500ml (Pack Centre)', 'sales'),
    (62, '2026-03-13 12:00:00.000000', 9.32, 'Packaging', '1.0 bags of Flat Lid BIOPAK (Pack Centre)', 'sales'),
    (63, '2026-03-14 12:00:00.000000', 7.43, 'Ingredients', '1.0 bags of Pams Frozen Strawberry (Pak n save)', 'sales'),
    (64, '2026-03-18 12:00:00.000000', 8.99, 'Ingredients', '1.0 jars of Lotus Biscoff (Pak n Save)', 'sales'),
    (65, '2026-03-18 12:00:00.000000', 3.6, 'Other', '1.0 bags of Ice 2kg (Woolworths)', 'sales'),
    (66, '2026-03-19 12:00:00.000000', 36.0, 'Ingredients', '1.0 bags of Thea Matcha 50g (The Matcha)', 'sales'),
    (67, '2026-03-19 12:00:00.000000', 64.0, 'Ingredients', '1.0 bags of Thea Matcha 100g (Thea Matcha)', 'sales');

SELECT setval(pg_get_serial_sequence('expenses', 'id'), 67, true);

INSERT INTO "inventory" ("id", "name", "category", "quantity", "unit", "cost_per_unit", "date_purchased", "notes") VALUES
    (1, 'Ferna Primera Ube', 'Syrups & Flavours', 3.0, 'bottles', 3.95, '2026-03-06 12:00:00.000000', 'Tita Christy'),
    (3, 'Otis Oat Milk', 'Dairy', 7.0, 'cartons', 3.89, '2026-03-14 00:00:00.000000', 'Woolworths'),
    (4, 'UFC Refresh Coconut Water 1L', 'Other', 13.0, 'cartons', 3.99, '2026-03-14 00:00:00.000000', 'Pak n Save'),
    (6, 'Anchor Cream 2L', 'Dairy', 2.0, 'bottles', 16.75, '2026-03-18 00:00:00.000000', 'Pak n Save'),
    (7, 'Jersey Condensed Mlk Ube', 'Syrups & Flavours', 1.0, 'jars', 4.99, '2026-03-08 12:00:00.000000', 'Tita Christy'),
    (8, 'Goldena Sago''t Gulaman Syrup', 'Syrups & Flavours', 3.0, 'cartons', 13.95, '2026-03-15 00:00:00.000000', 'Tita Christy'),
    (9, 'Nestle Highlander Condensed Mlk', 'Syrups & Flavours', 2.0, 'jars', 3.99, '2026-03-18 00:00:00.000000', 'Pak n Save'),
    (10, 'Anchor Cream 500ml', 'Dairy', 1.0, 'bottles', 4.72, '2026-03-14 00:00:00.000000', 'Pak n Save'),
    (11, 'Strawberry 350g (Fresh)', 'Other', 0.0, 'boxes', 4.5, '2026-03-22 12:00:00.000000', 'Woolworth'),
    (13, 'Gloves', 'Equipment', 1.0, 'cartons', 12.78, '2026-03-05 12:00:00.000000', 'Look sharp'),
    (14, 'Ziplock 125pcs', 'Packaging', 1.0, 'cartons', 4.5, '2026-03-28 12:00:00.000000', 'Looksharp'),
    (15, 'double wall cups', 'Packaging', 0.0, 'bags', 6.0, '2026-03-08 12:00:00.000000', 'Looksharp (Used Lids only)'),
    (16, '3pc Squeeze Bottle', 'Equipment', 1.0, 'bags', 5.0, '2026-03-08 12:00:00.000000', 'Looksharp'),
    (17, '420ML tall cups', 'Packaging', 0.0, 'bags', 4.5, '2026-03-01 12:00:00.000000', 'Warehouse (used for weekend pour)'),
    (18, 'Bio Clear Cup PLA 420ml 50s', 'Packaging', 1.0, 'bags', 14.93, '2026-02-26 12:00:00.000000', 'Gilmours'),
    (20, 'Bio Clear Cup PLA 500ml 50s', 'Packaging', 1.0, 'bags', 14.93, '2026-02-26 12:00:00.000000', 'Gilmours'),
    (21, 'Bio Clear Lids 100pk', 'Packaging', 1.0, 'bags', 9.72, '2026-02-26 12:00:00.000000', 'Gilmours'),
    (22, 'Coastal Napkin 100ea', 'Cleaning', 1.0, 'bags', 2.5, '2026-03-05 12:00:00.000000', 'Gilmours'),
    (23, '2 Cup Carrier Tray', 'Packaging', 1.0, 'bags', 12.78, '2026-03-05 12:00:00.000000', 'Gilmours'),
    (24, 'Sugarcane Straw 100pk', 'Packaging', 1.0, 'cartons', 5.98, '2026-03-05 12:00:00.000000', 'Gilmours'),
    (25, 'Kitchen Towel', 'Cleaning', 1.0, 'bags', 4.15, '2026-03-06 12:00:00.000000', 'Woolworth'),
    (26, 'Party Ice 3kg', 'Other', 1.0, 'cartons', 5.2, '2026-03-15 00:00:00.000000', 'Bell Block Supermarket'),
    (27, 'Laffare Gusto Plunger 200g', 'Coffee', 1.0, 'bags', 8.49, '2026-03-04 12:00:00.000000', 'Pak n Save'),
    (28, 'Display Stand', 'Equipment', 4.0, 'pcs', 3.9, '2026-03-08 12:00:00.000000', 'LookSharp'),
    (29, 'Thea Matcha 100g', 'Coffee', 2.0, 'bags', 64.0, '2026-03-19 12:00:00.000000', 'Thea Matcha'),
    (30, 'Elufa Ube Powder 1kg', 'Syrups & Flavours', 1.0, 'bags', 35.0, '2026-02-24 12:00:00.000000', 'Eve''s Shoppe'),
    (31, 'Milklab Oat Milk', 'Dairy', 1.0, 'cartons', 5.36, '2026-03-08 12:00:00.000000', 'Aitkens'),
    (32, 'Glass PET plastic 420ML', 'Packaging', 1.0, 'bags', 11.82, '2026-03-13 12:00:00.000000', 'Hardy Packaging'),
    (33, 'LID Domed for 420ML PET', 'Packaging', 1.0, 'bags', 7.8, '2026-03-13 12:00:00.000000', 'Hardy Packaging'),
    (34, 'BIOPAK Clear 500ml', 'Packaging', 1.0, 'bags', 16.82, '2026-03-13 12:00:00.000000', 'Pack Centre'),
    (35, 'Flat Lid BIOPAK', 'Packaging', 1.0, 'bags', 9.32, '2026-03-13 12:00:00.000000', 'Pack Centre'),
    (36, 'Pams Frozen Strawberry', 'Syrups & Flavours', 1.0, 'bags', 7.43, '2026-03-14 12:00:00.000000', 'Pak n save'),
    (37, 'Lotus Biscoff', 'Dairy', 1.0, 'jars', 8.99, '2026-03-18 12:00:00.000000', 'Pak n Save'),
    (38, 'Ice 2kg', 'Other', 1.0, 'bags', 3.6, '2026-03-18 12:00:00.000000', 'Woolworths'),
    (39, 'Thea Matcha 50g', 'Coffee', 1.0, 'bags', 36.0, '2026-03-19 12:00:00.000000', 'The Matcha');

SELECT setval(pg_get_serial_sequence('inventory', 'id'), 39, true);

INSERT INTO "menu_items" ("id", "name", "price", "category", "is_hidden", "is_sold_out") VALUES
    (1, 'Matcha Latte', 7.0, 'Matcha Series', FALSE, FALSE),
    (2, 'Strawberry Matcha', 10.0, 'Matcha Series', FALSE, FALSE),
    (3, 'Ube Cream Matcha', 8.0, 'Matcha Series', FALSE, FALSE),
    (4, 'Ube Cream Cold Brew', 8.0, 'Cold Brew Series', FALSE, FALSE),
    (5, 'Black Pearl Cold Brew', 8.0, 'Cold Brew Series', FALSE, FALSE),
    (6, 'Cold Brew', 6.0, 'Cold Brew Series', FALSE, FALSE),
    (7, 'Twilight Cloud', 8.0, 'Cloud Series', FALSE, FALSE),
    (8, 'Black Pearl Cloud', 8.0, 'Cloud Series', FALSE, FALSE),
    (9, 'Almond Milk', 1.0, 'Add Ons', FALSE, FALSE),
    (10, 'Regular Milk', 0.0, 'Add Ons', FALSE, FALSE),
    (11, 'Earl Grey Syrup', 0.5, 'Add Ons', FALSE, FALSE),
    (12, 'Ube Syrup', 0.5, 'Add Ons', FALSE, FALSE),
    (13, 'Strawberry Syrup', 0.5, 'Add Ons', FALSE, FALSE),
    (14, 'Black Pearl Syrup', 0.5, 'Add Ons', FALSE, FALSE),
    (15, 'Grande', 1.0, 'Sizes', FALSE, FALSE),
    (16, 'Venti', 2.0, 'Sizes', FALSE, FALSE),
    (17, 'Oat Milk', 0.5, 'Add Ons', FALSE, FALSE),
    (19, 'Spanish Latte Cold Brew', 8.0, 'Cold Brew Series', FALSE, FALSE),
    (20, 'Iced Chocolate', 6.0, 'Chocolate Series', FALSE, FALSE),
    (21, 'Clover Cloud', 8.0, 'Cloud Series', FALSE, FALSE),
    (22, 'Earl Grey Matcha', 8.0, 'Matcha Series', FALSE, FALSE),
    (23, 'Brown Sugar Cold Brew', 8.0, 'Cold Brew Series', FALSE, FALSE),
    (24, 'Biscoff Latte', 8.0, 'Coffee Series', FALSE, FALSE),
    (25, 'Ube Spanish Latte', 8.0, 'Coffee Series', FALSE, FALSE),
    (26, 'Spanish Latte', 8.0, 'Coffee Series', FALSE, FALSE),
    (27, 'Delivery Fee', 2.0, 'Extra Fees', FALSE, FALSE),
    (28, 'Biscoff Matcha', 8.0, 'Matcha Series', FALSE, FALSE);

SELECT setval(pg_get_serial_sequence('menu_items', 'id'), 28, true);

INSERT INTO "preorders" ("id", "customer_name", "pickup_time", "items", "notes", "status", "created_at") VALUES
    (4, 'Ate Kim - Summerset', '2026-03-07 02:00:00.000000', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}]'::jsonb, 'Delivery to Summerset', 'done', '2026-03-06 10:00:51.464180'),
    (5, 'Sean', '2026-03-14 02:15:00.000000', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 2}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 'Pick up before 3:30PM', 'done', '2026-03-13 09:58:01.966358'),
    (7, 'Charlotte', '2026-03-14 03:00:00.000000', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 8.0, "quantity": 1}, {"id": "5", "name": "Black Pearl Cold Brew", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 4}, {"id": "21", "name": "Clover Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 'Black Pearl is takeaway and no ice', 'done', '2026-03-13 20:44:15.535754'),
    (8, 'Clayr', '2026-03-15 02:01:00.000000', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 'Pick up', 'done', '2026-03-14 21:48:24.668766'),
    (9, 'Shenee', '2026-03-14 23:20:00.000000', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 'Delivery to Summerset
will pay in cash', 'done', '2026-03-15 11:12:02.455550'),
    (10, 'AM J', '2026-03-26 04:15:00.000000', '[{"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}]'::jsonb, 'Pick up at 5:15', 'done', '2026-03-19 15:44:31.976113'),
    (11, 'Mirra', '2026-03-18 21:00:00.000000', '[{"id": "1", "name": "Matcha Latte", "price": 7.0, "quantity": 1}]'::jsonb, 'Almond with Honey Preferrably', 'done', '2026-03-19 22:52:46.833456');

SELECT setval(pg_get_serial_sequence('preorders', 'id'), 11, true);

INSERT INTO "sales" ("id", "date", "items", "subtotal", "payment_method", "daily_order_number", "customer_name", "discount") VALUES
    (1, '2026-02-28 12:00:00.000000', '[{"id": "manual", "name": "2x Ube Matcha", "price": 14.0, "quantity": 1}]'::jsonb, 14.0, 'Bank Transfer', 1, 'Ate Dannise', 0.0),
    (2, '2026-02-28 14:00:00.000000', '[{"id": "manual", "name": "1x Spanish Latte CB + 1x Twilight Cloud", "price": 14.0, "quantity": 1}]'::jsonb, 14.0, 'Bank Transfer', 2, 'Charlotte', 0.0),
    (3, '2026-02-28 14:30:00.000000', '[{"id": "manual", "name": "1x Ube CB and 1x Spanish Latte CB", "price": 16.0, "quantity": 1}]'::jsonb, 16.0, 'Cash', 3, 'Kaye', 0.0),
    (4, '2026-02-28 16:00:00.000000', '[{"id": "manual", "name": "1x BS CB 1x BP CB 1x S Matcha 1x OG Matcha", "price": 33.0, "quantity": 1}]'::jsonb, 33.0, 'Bank Transfer', 4, 'Charlotte', 0.0),
    (5, '2026-02-28 13:00:00.000000', '[{"id": "manual", "name": "2x Ube Matcha", "price": 14.0, "quantity": 1}]'::jsonb, 14.0, 'Bank Transfer', 5, 'Ate Dannica', 0.0),
    (7, '2026-02-27 19:00:00.000000', '[{"id": "manual", "name": "1x Twilight Cloud", "price": 5.0, "quantity": 1}]'::jsonb, 5.0, 'Cash', 1, 'Kuya Kenneth', 0.0),
    (8, '2026-03-01 10:00:00.000000', '[{"id": "manual", "name": "1x Ube CB 1x Twilight Cloud", "price": 16.0, "quantity": 1}]'::jsonb, 16.0, 'Cash', 1, 'Glenn', 0.0),
    (9, '2026-03-01 09:00:00.000000', '[{"id": "manual", "name": "1x Twilight Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 1, 'Glenn', 0.0),
    (10, '2026-03-01 10:00:00.000000', '[{"id": "manual", "name": "1x Twilight Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 2, 'Glenn', 0.0),
    (11, '2026-03-01 20:00:00.000000', '[{"id": "manual", "name": "1x Strawberry Matcha", "price": 10.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 3, 'Clayr', 0.0),
    (12, '2026-03-01 20:00:00.000000', '[{"id": "manual", "name": "1x BP CB", "price": 7.0, "quantity": 1}]'::jsonb, 7.0, 'Bank Transfer', 4, 'Tita Janet', 0.0),
    (13, '2026-03-01 09:00:00.000000', '[{"id": "manual", "name": "2x Ube Matcha", "price": 16.0, "quantity": 1}]'::jsonb, 16.0, 'Bank Transfer', 5, 'Tita Tess', 0.0),
    (14, '2026-03-01 09:00:00.000000', '[{"id": "manual", "name": "1x Ube CB 2x Twilight Cloud", "price": 24.0, "quantity": 1}]'::jsonb, 24.0, 'Bank Transfer', 6, 'Glenn', 0.0),
    (15, '2026-03-01 20:00:00.000000', '[{"id": "manual", "name": "clover cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 1, 'kuya', 0.0),
    (16, '2026-03-06 15:45:00.000000', '[{"id": "manual", "name": "Ube Cream Cold Brew ×3, Grande ×3, Iced Chocolate ×1", "price": 30.0, "quantity": 1}]'::jsonb, 30.0, 'Bank Transfer', 1, 'Ate Danisse', 0.0),
    (17, '2026-03-06 15:30:00.000000', '[{"id": "manual", "name": "Ube Cream Cold Brew ×3, Grande ×3", "price": 24.0, "quantity": 1}]'::jsonb, 24.0, 'Bank Transfer', 2, 'Ate Kim', 0.0),
    (18, '2026-02-27 09:00:00.000000', '[{"id": "manual", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 2, 'Lilyannah', 0.0),
    (19, '2026-02-28 09:00:00.000000', '[{"id": "21", "name": "Clover Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 6, NULL, 0.0),
    (20, '2026-03-07 10:10:16.941240', '[{"id": "2", "name": "Strawberry Matcha", "price": 10.0, "quantity": 1}, {"id": "5", "name": "Black Pearl Cold Brew", "price": 7.0, "quantity": 2}]'::jsonb, 24.0, 'Bank Transfer', 3, NULL, 0.0),
    (21, '2026-03-07 10:19:58.826427', '[{"id": "2", "name": "Strawberry Matcha", "price": 10.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 12.0, 'Cash', 4, NULL, 0.0),
    (22, '2026-03-07 10:36:14.621844', '[{"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 17.0, 'Cash', 3, NULL, 0.0),
    (23, '2026-03-07 10:42:43.470935', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 4, NULL, 0.0),
    (24, '2026-03-07 10:45:41.921044', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 5, NULL, 0.0),
    (25, '2026-03-07 11:25:11.921467', '[{"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 6, NULL, 0.0),
    (26, '2026-03-07 11:26:46.577846', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 7.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 7, NULL, 0.0),
    (27, '2026-03-07 11:30:24.028421', '[{"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 8, NULL, 0.0),
    (28, '2026-03-07 11:31:06.795385', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 9.0, 'Cash', 9, NULL, 0.0),
    (29, '2026-03-07 11:31:57.628134', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 9.0, 'Cash', 10, NULL, 0.0),
    (30, '2026-03-07 11:41:52.316044', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 11, NULL, 0.0),
    (31, '2026-03-07 11:44:57.771692', '[{"id": "21", "name": "Clover Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 12, NULL, 0.0),
    (32, '2026-03-07 11:46:44.937217', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 13, NULL, 0.0),
    (33, '2026-03-07 11:48:54.852554', '[{"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 14, NULL, 0.0),
    (34, '2026-03-07 11:50:51.606647', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 15, NULL, 0.0),
    (35, '2026-03-07 12:02:11.808481', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 2}]'::jsonb, 16.0, 'Cash', 16, NULL, 0.0),
    (36, '2026-03-07 12:04:22.714557', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}, {"id": "5", "name": "Black Pearl Cold Brew", "price": 7.0, "quantity": 1}]'::jsonb, 19.0, 'Bank Transfer', 17, NULL, 0.0),
    (37, '2026-03-07 12:07:50.478916', '[{"id": "18", "name": "Carrier Takeaway Tray", "price": 1.0, "quantity": 1}]'::jsonb, 1.0, 'Cash', 18, NULL, 0.0),
    (38, '2026-03-07 12:25:23.026115', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}]'::jsonb, 16.0, 'Cash', 19, NULL, 0.0),
    (39, '2026-03-07 12:28:50.580260', '[{"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 20, NULL, 0.0),
    (40, '2026-03-07 12:33:51.715695', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "4", "name": "Ube Cream Cold Brew", "price": 7.0, "quantity": 1}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}, {"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}]'::jsonb, 46.0, 'Bank Transfer', 21, NULL, 0.0),
    (41, '2026-03-07 12:36:42.640529', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 22, NULL, 0.0),
    (42, '2026-03-07 12:49:55.064174', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 23, NULL, 0.0),
    (43, '2026-03-07 12:53:23.957766', '[{"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}, {"id": "11", "name": "Earl Grey Syrup", "price": 0.5, "quantity": 1}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 16.5, 'Bank Transfer', 24, NULL, 0.0),
    (44, '2026-03-07 12:57:46.933573', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 25, NULL, 0.0),
    (45, '2026-03-07 13:01:53.807280', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 26, NULL, 0.0),
    (46, '2026-03-07 13:06:16.933771', '[{"id": "5", "name": "Black Pearl Cold Brew", "price": 7.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 27, NULL, 0.0),
    (47, '2026-03-07 13:06:28.201731', '[{"id": "5", "name": "Black Pearl Cold Brew", "price": 7.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 28, NULL, 0.0),
    (48, '2026-03-07 13:15:24.830244', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 29, 'carlzon', 0.0),
    (49, '2026-03-07 13:16:58.671029', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 30, 'adriel', 0.0),
    (50, '2026-03-07 13:17:26.595787', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 2}]'::jsonb, 16.0, 'Bank Transfer', 31, 'Aimee', 0.0),
    (51, '2026-03-07 13:23:28.981706', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 32, NULL, 0.0),
    (52, '2026-03-07 13:25:35.021351', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 4}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 4}]'::jsonb, 40.0, 'Bank Transfer', 33, NULL, 0.0),
    (53, '2026-03-07 13:28:15.186099', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 18.0, 'Cash', 34, NULL, 0.0),
    (54, '2026-03-07 13:34:36.967189', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 35, NULL, 0.0),
    (55, '2026-03-07 13:35:56.247544', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 36, NULL, 0.0),
    (56, '2026-03-07 13:39:40.284093', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 37, NULL, 0.0),
    (57, '2026-03-07 13:41:05.805483', '[{"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 2.0, 'Bank Transfer', 38, NULL, 0.0),
    (58, '2026-03-07 13:49:45.861965', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 39, NULL, 0.0),
    (59, '2026-03-07 13:56:35.291232', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 3}]'::jsonb, 24.0, 'Cash', 40, NULL, 0.0),
    (60, '2026-03-07 14:11:51.617771', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 41, NULL, 0.0),
    (61, '2026-03-07 14:15:42.899156', '[{"id": "5", "name": "Black Pearl Cold Brew", "price": 7.0, "quantity": 1}]'::jsonb, 7.0, 'Bank Transfer', 42, NULL, 0.0),
    (62, '2026-03-07 14:16:03.644045', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 43, NULL, 0.0),
    (63, '2026-03-07 14:17:01.480299', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 44, NULL, 0.0),
    (64, '2026-03-07 14:20:30.651145', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 45, NULL, 0.0),
    (65, '2026-03-07 14:25:45.947647', '[{"id": "5", "name": "Black Pearl Cold Brew", "price": 7.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 9.0, 'Cash', 46, NULL, 0.0),
    (66, '2026-03-07 14:27:48.796755', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 7.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 9.0, 'Bank Transfer', 47, NULL, 0.0),
    (67, '2026-03-07 14:32:36.826059', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 7.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 9.0, 'Bank Transfer', 48, NULL, 0.0),
    (68, '2026-03-07 14:43:19.295440', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 49, NULL, 0.0),
    (69, '2026-03-07 14:50:09.925489', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}]'::jsonb, 20.0, 'Bank Transfer', 50, NULL, 0.0),
    (70, '2026-03-07 14:57:01.931072', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 51, NULL, 3.0),
    (71, '2026-03-07 15:08:19.759803', '[{"id": "6", "name": "Cold Brew", "price": 6.0, "quantity": 1}]'::jsonb, 6.0, 'Cash', 52, NULL, 0.0),
    (72, '2026-03-07 15:14:12.441438', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 53, NULL, 0.0),
    (73, '2026-03-07 15:36:34.208616', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 16.0, 'Bank Transfer', 54, NULL, 0.0),
    (74, '2026-03-07 15:44:39.024168', '[{"id": "5", "name": "Black Pearl Cold Brew", "price": 7.0, "quantity": 3}, {"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}]'::jsonb, 28.0, 'Bank Transfer', 55, NULL, 0.0),
    (75, '2026-03-07 15:50:24.374386', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 56, NULL, 0.0),
    (76, '2026-03-07 15:53:13.711224', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 57, NULL, 0.0),
    (77, '2026-03-07 15:53:59.965104', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 58, NULL, 0.0),
    (78, '2026-03-07 15:56:55.178164', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}]'::jsonb, 20.0, 'Bank Transfer', 59, NULL, 0.0),
    (79, '2026-03-07 15:56:57.574792', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 60, NULL, 0.0),
    (80, '2026-03-07 15:59:00.930577', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 61, NULL, 0.0),
    (81, '2026-03-07 16:07:36.835042', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 62, NULL, 0.0),
    (82, '2026-03-07 16:08:52.074092', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 7.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 9.0, 'Cash', 63, NULL, 0.0),
    (83, '2026-03-07 16:14:17.285758', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 64, NULL, 0.0),
    (84, '2026-03-07 16:16:10.837885', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 65, NULL, 0.0),
    (85, '2026-03-07 16:37:07.784857', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}, {"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 18.0, 'Bank Transfer', 66, NULL, 0.0),
    (86, '2026-03-07 16:38:51.951470', '[{"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 67, NULL, 0.0),
    (87, '2026-03-07 16:44:07.491695', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 68, NULL, 0.0),
    (88, '2026-03-07 16:49:30.452351', '[{"id": "5", "name": "Black Pearl Cold Brew", "price": 7.0, "quantity": 1}]'::jsonb, 7.0, 'Bank Transfer', 69, NULL, 0.0),
    (89, '2026-03-07 16:53:53.336618', '[{"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 70, NULL, 0.0),
    (90, '2026-03-07 17:07:06.496782', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 71, NULL, 0.0),
    (91, '2026-03-07 17:07:00.000000', '[{"id": "manual", "name": "Cold Brew", "price": 6.0, "quantity": 1}]'::jsonb, 6.0, 'Cash', 72, NULL, 0.0),
    (92, '2026-03-07 17:09:46.264119', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 3}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}]'::jsonb, 30.0, 'Bank Transfer', 73, NULL, 0.0),
    (93, '2026-03-07 17:11:03.592404', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 7.0, "quantity": 1}]'::jsonb, 7.0, 'Bank Transfer', 74, NULL, 0.0),
    (94, '2026-03-07 17:14:19.190470', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 75, NULL, 0.0),
    (95, '2026-03-07 17:16:01.798956', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 76, NULL, 0.0),
    (96, '2026-03-07 17:19:47.842428', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 77, NULL, 0.0),
    (97, '2026-03-07 17:21:48.576074', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 78, NULL, 0.0),
    (98, '2026-03-07 17:30:55.170723', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 79, NULL, 0.0),
    (99, '2026-03-07 17:31:42.284130', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 80, NULL, 0.0),
    (100, '2026-03-07 17:35:00.000000', '[{"id": "manual", "name": "Black Pearl Cloud ×1, Venti ×1", "price": 10.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 81, NULL, 0.0),
    (101, '2026-03-07 17:35:37.018563', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 82, NULL, 0.0),
    (102, '2026-03-07 17:41:19.554524', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 83, NULL, 0.0),
    (104, '2026-03-08 16:39:21.848954', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}]'::jsonb, 20.0, 'Bank Transfer', 2, 'Ate Kim - Summerset', 0.0),
    (105, '2026-03-08 19:19:11.814725', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 3}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}]'::jsonb, 30.0, 'Bank Transfer', 3, 'Kuya Kenneth', 0.0),
    (106, '2026-03-09 17:22:00.400932', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 1, 'Shenee', 0.0),
    (107, '2026-03-09 17:22:09.343969', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 2, 'Tita Jo', 0.0),
    (108, '2026-03-11 18:06:09.402972', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}, {"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}, {"id": "12", "name": "Ube Syrup", "price": 0.5, "quantity": 2}]'::jsonb, 30.0, 'Bank Transfer', 1, 'Ate Sheryl', 0.0),
    (109, '2026-03-12 17:36:05.130179', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}, {"id": "4", "name": "Ube Cream Cold Brew", "price": 7.0, "quantity": 1}, {"id": "12", "name": "Ube Syrup", "price": 0.5, "quantity": 2}]'::jsonb, 20.0, 'Bank Transfer', 1, 'ate kim', 0.0),
    (110, '2026-03-12 17:36:12.967540', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 3}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}]'::jsonb, 30.0, 'Bank Transfer', 2, NULL, 0.0),
    (111, '2026-03-13 11:56:01.709341', '[{"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 1, 'Friend ni Chelsea', 0.0),
    (112, '2026-03-13 11:56:31.131428', '[{"id": "19", "name": "Spanish Latte Cold Brew", "price": 7.0, "quantity": 1}, {"id": "15", "name": "Grande", "price": 1.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 2, 'Chelsea', 0.0),
    (113, '2026-03-13 13:31:58.911587', '[{"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 3, 'friend ni chelsea', 0.0),
    (114, '2026-03-13 15:25:10.866383', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 2}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 42.0, 'Bank Transfer', 4, 'Sean', 0.0),
    (115, '2026-03-14 15:51:34.535733', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}]'::jsonb, 20.0, 'Cash', 1, 'Maricris', 0.0),
    (116, '2026-03-14 16:28:30.348776', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 8.0, "quantity": 1}, {"id": "5", "name": "Black Pearl Cold Brew", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 4}, {"id": "21", "name": "Clover Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 40.0, 'Bank Transfer', 2, 'Charlotte', 0.0),
    (117, '2026-03-15 08:32:15.927401', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "22", "name": "Earl Grey Matcha", "price": 8.0, "quantity": 1}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "23", "name": "Brown Sugar Cold Brew", "price": 8.0, "quantity": 1}]'::jsonb, 32.0, 'Bank Transfer', 1, 'Sam', 0.0),
    (118, '2026-03-15 12:31:29.302596', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 2, 'Shenee', 0.0),
    (119, '2026-03-15 12:31:53.792576', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 30.0, 'Bank Transfer', 3, 'Kuya Kenneth', 0.0),
    (120, '2026-03-15 14:30:23.703818', '[{"id": "24", "name": "Biscoff Latte", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 4, 'Bethamie', 0.0),
    (121, '2026-03-15 16:56:44.515058', '[{"id": "26", "name": "Spanish Latte", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Cash', 5, 'Papa', 0.0),
    (122, '2026-03-15 16:56:00.000000', '[{"id": "manual", "name": "Ube Spanish Latte×1, Venti ×1", "price": 10.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 6, 'Clayr', 0.0),
    (123, '2026-03-15 18:22:52.587168', '[{"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 2}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 30.0, 'Cash', 7, NULL, 0.0),
    (124, '2026-03-18 17:50:05.860319', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 8.0, "quantity": 3}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}]'::jsonb, 30.0, 'Bank Transfer', 1, 'Ate Sheril', 0.0),
    (125, '2026-03-18 17:50:15.983541', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 2, 'Tita Jo', 0.0),
    (126, '2026-03-18 18:39:19.627276', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}, {"id": "27", "name": "Delivery Fee", "price": 2.0, "quantity": 1}]'::jsonb, 12.0, 'Bank Transfer', 3, 'Bethamie', 0.0),
    (127, '2026-03-18 19:58:25.402865', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}]'::jsonb, 8.0, 'Bank Transfer', 4, 'friend ni bethamie', 0.0),
    (128, '2026-03-19 18:13:59.303049', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 3}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 6}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 3}]'::jsonb, 60.0, 'Bank Transfer', 1, 'Anty Cora', 0.0),
    (129, '2026-03-19 18:14:21.011200', '[{"id": "1", "name": "Matcha Latte", "price": 8.0, "quantity": 1}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 3}]'::jsonb, 30.0, 'Bank Transfer', 2, 'AM J', 0.0),
    (130, '2026-03-20 09:27:30.333450', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 1, 'kuya kenneth', 0.0),
    (131, '2026-03-20 14:25:28.094920', '[{"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Bank Transfer', 2, 'Kuya', 0.0),
    (132, '2026-03-20 14:33:30.874603', '[{"id": "1", "name": "Matcha Latte", "price": 7.0, "quantity": 1}]'::jsonb, 7.0, 'Bank Transfer', 3, 'Mirra', 0.0),
    (133, '2026-03-21 17:00:19.390514', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 8.0, "quantity": 1}, {"id": "2", "name": "Strawberry Matcha", "price": 10.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}]'::jsonb, 22.0, 'Bank Transfer', 1, 'Rysher', 0.0),
    (134, '2026-03-21 17:00:47.192940', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}, {"id": "27", "name": "Delivery Fee", "price": 2.0, "quantity": 1}]'::jsonb, 12.0, 'Bank Transfer', 2, 'Jeosh', 1.0),
    (135, '2026-03-21 17:23:03.702905', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}]'::jsonb, 20.0, 'Bank Transfer', 3, 'Tita Jo', 0.0),
    (136, '2026-03-22 14:23:10.352566', '[{"id": "4", "name": "Ube Cream Cold Brew", "price": 8.0, "quantity": 1}, {"id": "2", "name": "Strawberry Matcha", "price": 10.0, "quantity": 2}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 2}, {"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 2}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "5", "name": "Black Pearl Cold Brew", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 9}]'::jsonb, 94.0, 'Bank Transfer', 1, 'Ronna', 0.0),
    (137, '2026-03-22 14:23:59.390435', '[{"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 2, NULL, 1.0),
    (138, '2026-03-22 14:24:31.240534', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 2}]'::jsonb, 24.0, 'Cash', 3, 'els', 0.0),
    (139, '2026-03-22 14:25:47.436879', '[{"id": "2", "name": "Strawberry Matcha", "price": 10.0, "quantity": 4}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 4}]'::jsonb, 48.0, 'Cash', 4, 'Philip', 0.0),
    (140, '2026-03-22 18:03:02.168401', '[{"id": "28", "name": "Biscoff Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 5, 'Denise', 0.0),
    (141, '2026-03-22 18:03:43.244745', '[{"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}, {"id": "8", "name": "Black Pearl Cloud", "price": 8.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 6, 'Eli', 0.0),
    (142, '2026-03-22 18:12:06.663842', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 4}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 4}]'::jsonb, 40.0, 'Bank Transfer', 7, 'Glenn', 0.0),
    (143, '2026-03-22 21:03:41.483234', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 1}]'::jsonb, 10.0, 'Cash', 8, 'Denise', 0.0),
    (144, '2026-03-22 21:04:07.094707', '[{"id": "7", "name": "Twilight Cloud", "price": 8.0, "quantity": 1}, {"id": "3", "name": "Ube Cream Matcha", "price": 8.0, "quantity": 1}, {"id": "16", "name": "Venti", "price": 2.0, "quantity": 2}]'::jsonb, 20.0, 'Cash', 9, 'Kuya', 0.0);

SELECT setval(pg_get_serial_sequence('sales', 'id'), 144, true);

INSERT INTO "stock_logs" ("id", "date", "item_id", "item_name", "category", "action", "delta", "quantity_after", "unit", "notes") VALUES
    (1, '2026-03-08 19:32:28.568003', 29, 'Thea Matcha 100g', 'Coffee', 'restocked', 1.0, 2.0, 'bags', NULL),
    (2, '2026-03-08 19:32:53.155250', 29, 'Thea Matcha 100g', 'Coffee', 'used', -1.0, 1.0, 'bags', NULL),
    (3, '2026-03-08 19:33:04.411452', 21, 'Bio Clear Lids 100pk', 'Packaging', 'used', -1.0, 1.0, 'bags', NULL),
    (4, '2026-03-08 19:33:10.321702', 20, 'Bio Clear Cup PLA 500ml 50s', 'Packaging', 'used', -1.0, 1.0, 'bags', NULL),
    (5, '2026-03-08 20:04:38.002416', 1, 'Ferna Primera Ube', 'Syrups & Flavours', 'used', -3.0, 3.0, 'bottles', NULL),
    (6, '2026-03-08 20:05:03.485926', 3, 'Otis Oat Milk', 'Dairy', 'used', -6.0, 8.0, 'cartons', NULL),
    (7, '2026-03-08 20:06:02.356429', 3, 'Otis Oat Milk', 'Dairy', 'used', -7.0, 1.0, 'cartons', NULL),
    (8, '2026-03-08 20:20:35.621266', 31, 'Milklab Oat Milk', 'Dairy', 'used', -7.0, 1.0, 'cartons', NULL),
    (9, '2026-03-09 17:25:34.544045', 17, '420ML tall cups', 'Packaging', 'used', -2.0, 0.0, 'bags', NULL),
    (10, '2026-03-10 01:33:54.936202', 9, 'Nestle Highlander Condensed Mlk', 'Syrups & Flavours', 'used', -1.0, 1.0, 'jars', NULL),
    (11, '2026-03-10 01:34:54.553137', 4, 'UFC Refresh Coconut Water 1L', 'Other', 'used', -6.0, 0.0, 'cartons', NULL),
    (12, '2026-03-10 01:35:07.051394', 4, 'UFC Refresh Coconut Water 1L', 'Other', 'restocked', 2.0, 2.0, 'cartons', NULL),
    (13, '2026-03-10 01:35:11.516745', 4, 'UFC Refresh Coconut Water 1L', 'Other', 'used', -1.0, 1.0, 'cartons', NULL),
    (14, '2026-03-10 01:35:33.150829', 29, 'Thea Matcha 100g', 'Coffee', 'used', -1.0, 0.0, 'bags', NULL),
    (15, '2026-03-11 00:07:39.589713', 9, 'Nestle Highlander Condensed Mlk', 'Syrups & Flavours', 'restocked', 3.0, 4.0, 'jars', NULL),
    (16, '2026-03-11 00:07:50.746829', 4, 'UFC Refresh Coconut Water 1L', 'Other', 'restocked', 2.0, 3.0, 'cartons', NULL),
    (17, '2026-03-11 00:08:01.239871', 3, 'Otis Oat Milk', 'Dairy', 'restocked', 4.0, 5.0, 'cartons', NULL),
    (18, '2026-03-12 08:11:03.008475', 26, 'Party Ice 3kg', 'Other', 'used', -1.0, 0.0, 'cartons', NULL),
    (19, '2026-03-12 08:11:09.188877', 29, 'Thea Matcha 100g', 'Coffee', 'restocked', 1.0, 1.0, 'bags', NULL),
    (20, '2026-03-12 08:11:32.031288', 4, 'UFC Refresh Coconut Water 1L', 'Other', 'used', -2.0, 2.0, 'cartons', NULL),
    (21, '2026-03-12 08:11:47.815916', 3, 'Otis Oat Milk', 'Dairy', 'used', -2.0, 3.0, 'cartons', NULL),
    (22, '2026-03-12 08:12:03.367111', 9, 'Nestle Highlander Condensed Mlk', 'Syrups & Flavours', 'used', -1.0, 3.0, 'jars', NULL),
    (23, '2026-03-14 18:31:21.175747', 3, 'Otis Oat Milk', 'Dairy', 'used', -2.0, 1.0, 'cartons', NULL),
    (24, '2026-03-14 18:31:28.308187', 3, 'Otis Oat Milk', 'Dairy', 'restocked', 6.0, 7.0, 'cartons', NULL),
    (25, '2026-03-14 18:31:42.375446', 4, 'UFC Refresh Coconut Water 1L', 'Other', 'used', -1.0, 1.0, 'cartons', NULL),
    (26, '2026-03-14 18:31:47.242013', 4, 'UFC Refresh Coconut Water 1L', 'Other', 'restocked', 12.0, 13.0, 'cartons', NULL),
    (27, '2026-03-14 18:32:05.277169', 10, 'Anchor Cream 500ml', 'Dairy', 'restocked', 1.0, 1.0, 'bottles', NULL),
    (28, '2026-03-15 11:28:19.306465', 8, 'Goldena Sago''t Gulaman Syrup', 'Syrups & Flavours', 'restocked', 1.0, 2.0, 'cartons', NULL),
    (29, '2026-03-15 11:28:19.914860', 8, 'Goldena Sago''t Gulaman Syrup', 'Syrups & Flavours', 'restocked', 1.0, 3.0, 'cartons', NULL),
    (30, '2026-03-15 12:42:19.903336', 26, 'Party Ice 3kg', 'Other', 'restocked', 1.0, 1.0, 'cartons', NULL),
    (31, '2026-03-18 20:56:34.321121', 6, 'Anchor Cream 2L', 'Dairy', 'restocked', 1.0, 2.0, 'bottles', NULL),
    (32, '2026-03-18 20:56:49.710590', 9, 'Nestle Highlander Condensed Mlk', 'Syrups & Flavours', 'used', -2.0, 1.0, 'jars', NULL),
    (33, '2026-03-18 20:56:51.146884', 9, 'Nestle Highlander Condensed Mlk', 'Syrups & Flavours', 'restocked', 1.0, 2.0, 'jars', NULL),
    (34, '2026-03-18 20:56:51.637563', 9, 'Nestle Highlander Condensed Mlk', 'Syrups & Flavours', 'restocked', 1.0, 3.0, 'jars', NULL),
    (35, '2026-03-19 16:00:18.434341', 29, 'Thea Matcha 100g', 'Coffee', 'restocked', 1.0, 2.0, 'bags', NULL),
    (36, '2026-03-19 16:01:08.236880', 29, 'Thea Matcha 100g', 'Coffee', 'restocked', 1.0, 2.0, 'bags', NULL);

SELECT setval(pg_get_serial_sequence('stock_logs', 'id'), 36, true);

INSERT INTO "tabs" ("id", "customer_name", "amount", "direction", "description", "date", "status", "settled_at") VALUES
    (1, 'Shaun', 70.0, 'i_owe', 'Expenses', '2026-03-07 00:35:59.112377', 'open', NULL),
    (2, 'Kuya', 20.0, 'they_owe', '1x Twilight 2x Clover Cloud', '2026-03-07 00:36:30.191313', 'settled', '2026-03-07 16:28:46.112914'),
    (3, 'KUYA', 10.0, 'they_owe', '1x BP cloud', '2026-03-07 16:29:26.217053', 'settled', '2026-03-18 21:06:05.804074'),
    (4, 'Kuya', 50.0, 'they_owe', '2x Twilight Venti, 1x Ube Matcha', '2026-03-18 21:06:25.855786', 'open', NULL);

SELECT setval(pg_get_serial_sequence('tabs', 'id'), 4, true);

COMMIT;